/* ================= SCHEDULES STATE ==================== */
export const SCHEDULES_REQUEST = "SCHEDULES_REQUEST"
export const SCHEDULES_REQUEST_SUCCESS = "SCHEDULES_REQUEST_SUCCESS"
export const SCHEDULES_REQUEST_ERROR = "SCHEDULES_REQUEST_ERROR"

export const SCHEDULES_RESET = "SCHEDULES_RESET"
